
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Map;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class FIRST extends javax.swing.JFrame {
private HashMap<String, HashMap<String, Integer>> rentMap;
  private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    /**
     * Creates new form FIRST
     */
    public FIRST() {
        initComponents();
           try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fahim", "root", "12345678");
            pst = con.prepareStatement("select * from project2 ");
            rs = pst.executeQuery();
            
               if (rs.next()) {
               NAME.setText(rs.getString(1));
               MOBILE.setText(rs.getString(2)); 
               ADDRESS.setText(rs.getString(3));
               NID_NUMBER.setText(rs.getString(3));
                 
               
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

         initializeRentMap();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        NAME = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        MOBILE = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        okk = new javax.swing.JTextArea();
        ADDRESS = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        NID_NUMBER = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ok = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        submitt = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        NEXT = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Gazipur", "Tangail", "Kishoreganj", "Manikganj", "Munshiganj", "Narayanganj", "Narsingdi", "Faridpur", "Gopalganj", "Madaripur", "Rajbari", "Shariatpur" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 194, 175, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ADDRESS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 574, 72, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DESTINATION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 242, -1, 28));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NID NUMBER");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 617, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dhaka", "Gazipur", "Tangail", "Kishoreganj", "Manikganj", "Munshiganj", "Narayanganj", "Narsingdi", "Faridpur", "Gopalganj", "Madaripur", "Rajbari", "Shariatpur" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 245, 175, -1));

        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });
        getContentPane().add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 495, 197, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RENT AMOUNT");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 382, -1, 28));

        MOBILE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOBILEActionPerformed(evt);
            }
        });
        getContentPane().add(MOBILE, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 535, 197, -1));

        okk.setColumns(20);
        okk.setRows(5);
        jScrollPane2.setViewportView(okk);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 382, 179, 39));

        ADDRESS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDRESSActionPerformed(evt);
            }
        });
        getContentPane().add(ADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 571, 197, -1));

        button.setText("BUTTON");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 342, -1, -1));

        NID_NUMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NID_NUMBERActionPerformed(evt);
            }
        });
        getContentPane().add(NID_NUMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 614, 197, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("QuickTrip Car Rentals");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 525, 106));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CUSTOMER INFORMATION");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 439, -1, 44));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEDAN", "MINI VAN", "SUV", "HATCHBACK", "TRUCK" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 193, 28));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vehical Type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 91, 28));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Available Vehical");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOYOTA CAMRY", "TOYOTA SIENNA", "HONDA CR-V", "VOLKSWAGEN GOLF", "FORD F-150" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 193, 28));

        ok.setColumns(20);
        ok.setRows(5);
        jScrollPane1.setViewportView(ok);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 305, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TOUR INFORMATION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 130, -1, 43));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NAME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 497, 72, 19));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("STARTING");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 191, -1, 28));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MOBILE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 538, 72, -1));

        submitt.setText("SUBMITT");
        submitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submittActionPerformed(evt);
            }
        });
        getContentPane().add(submitt, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 591, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 183, 43));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 298, 175, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DAYS");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 288, 75, 43));

        NEXT.setText("NEXT");
        NEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXTActionPerformed(evt);
            }
        });
        getContentPane().add(NEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 591, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wallpaperflare.com_wallpaper (1).jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(-600, 10, 1480, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void MOBILEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOBILEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOBILEActionPerformed

    private void ADDRESSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDRESSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDRESSActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:updateRentAmount();
        updateRentAmount();
    }//GEN-LAST:event_buttonActionPerformed

    private void NID_NUMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NID_NUMBERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NID_NUMBERActionPerformed


    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
  String selectedVehicleType = (String) jComboBox1.getSelectedItem();
    System.out.println("Selected Vehicle Type: " + selectedVehicleType);

    switch (selectedVehicleType) {
        case "SEDAN":
            jComboBox2.setSelectedItem("TOYOTA CAMRY");
            ok.setText("Model: Toyota Camry\n" +
                "Seating Capacity: 5 passengers\n" +
                "Air Conditioning: Dual-zone climate control\n" +
                "Fuel Type: Gasoline ");
            break;
        
        case "MINI VAN":
            jComboBox2.setSelectedItem("TOYOTA SIENNA");
            ok.setText("Model: Toyota Sienna\n" +
                "Seating Capacity: 7 to 8 passengers\n" +
                "Air Conditioning: Tri-zone automatic climate control\n" +
                "Fuel Type: Hybrid (gasoline-electric hybrid only)");
            break;

        case "SUV":
            jComboBox2.setSelectedItem("HONDA CR-V");
            ok.setText("Model: Honda CR-V\n" +
                "Seating Capacity: 5 passengers\n" +
                "Air Conditioning: Yes\n" +
                "Fuel Type: Gasoline/Hybrid");
            break;

        case "HATCHBACK":
            jComboBox2.setSelectedItem("VOLKSWAGEN GOLF");
            ok.setText("Model: Volkswagen Golf\n" +
                "Seating Capacity: 5 passengers\n" +
                "Air Conditioning: Yes\n" +
                "Fuel Type: Gasoline/Diesel");
            break;

        case "TRUCK":
            jComboBox2.setSelectedItem("FORD F-150");
            ok.setText("Model: Ford F-150\n" +
                "Seating Capacity: 3-6 (varies by cab type)\n" +
                "Air Conditioning: Yes\n" +
                "Fuel Type: Gasoline/Diesel");
            break;

        default:
            jComboBox2.setSelectedItem(null);
            ok.setText(""); // Clear the JTextArea if no selection
            break;
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void submittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submittActionPerformed
   String name = NAME.getText();
    String address = ADDRESS.getText();
    String mobile = MOBILE.getText();
     String nid_number = NID_NUMBER.getText();
    
    try {
        // Prepare SQL statement to insert new entry
        String sql = "INSERT INTO project2 (NAME, MOBILE, ADDRESS,NID_NUMBER) VALUES (?, ?, ?,?)";
        PreparedStatement insertStatement = con.prepareStatement(sql);
        insertStatement.setString(1, name);
        insertStatement.setString(2, mobile);
        insertStatement.setString(3, address);
        insertStatement.setString(4, nid_number);

        // Execute the insert statement
        int rowsAffected = insertStatement.executeUpdate();
        
        if (rowsAffected > 0) {
            // Insert successful
            System.out.println("New customer entry added successfully!");
            
            // Clear text fields after successful insertion
            NAME.setText("");
            MOBILE.setText("");
            ADDRESS.setText("");
            NID_NUMBER.setText("");
        } else {
            // Insert failed
            System.out.println("Failed to add new customer entry.");
        }
        
        // Close the PreparedStatement
        insertStatement.close();
        
        // Refresh the table
    } catch (Exception ex) {
        System.out.println("Error adding new customer entry: " + ex);
    }
    }//GEN-LAST:event_submittActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // Parse rent from okk JTextArea
    String rentText = okk.getText().replace(" BDT", "");  // Remove "BDT" if it's in the text
    try {
        int baseRent = Integer.parseInt(rentText); // Convert rent to an integer
        int multiplier = Integer.parseInt((String) jComboBox5.getSelectedItem()); // Get selected number from jComboBox5
        int totalRent = baseRent * multiplier; // Calculate the total

        // Update okk with the new total rent
        okk.setText(totalRent + " BDT");

    } catch (NumberFormatException e) {
        okk.setText("Invalid rent value");
    }
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void NEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXTActionPerformed
        payment paymentPage = new payment();
    
    // Set the payment page as visible
    paymentPage.setVisible(true);
    
    // Optionally, hide the current form
    this.setVisible(false);
    
    
    }//GEN-LAST:event_NEXTActionPerformed

private void initializeRentMap() {
    rentMap = new HashMap<>(); // Initialize the class-level variable
    
    // Define base location rates for common locations
    HashMap<String, Integer> baseRates = new HashMap<>();
    baseRates.put("Dhaka", 1000);
    baseRates.put("Gazipur", 1200);
    baseRates.put("Tangail", 1500);
    baseRates.put("Kishoreganj", 1300);
    baseRates.put("Manikganj", 1400);
    baseRates.put("Munshiganj", 1500);
    baseRates.put("Narayanganj", 1600);
    baseRates.put("Narsingdi", 1700);
    baseRates.put("Faridpur", 1800);
    baseRates.put("Gopalganj", 1900);
    baseRates.put("Madaripur", 2000);
    baseRates.put("Rajbari", 2100);
    baseRates.put("Shariatpur", 2200);

    // Helper method to create vehicle type rates by scaling base rates
    rentMap.put("SEDAN", createVehicleRates(baseRates, 1.0));
    rentMap.put("MINI VAN", createVehicleRates(baseRates, 1.5));
    rentMap.put("SUV", createVehicleRates(baseRates, 1.3));
    rentMap.put("HATCHBACK", createVehicleRates(baseRates, 0.9));
    rentMap.put("TRUCK", createVehicleRates(baseRates, 2.0));
}

// Method to scale base rates by a given multiplier
private HashMap<String, Integer> createVehicleRates(HashMap<String, Integer> baseRates, double multiplier) {
    HashMap<String, Integer> vehicleRates = new HashMap<>();
    for (Map.Entry<String, Integer> entry : baseRates.entrySet()) {
        String location = entry.getKey();
        int rate = (int) (entry.getValue() * multiplier); // Scale base rate by multiplier
        vehicleRates.put(location, rate);
    }
    return vehicleRates;
}
// Method to update the rent amount based on selected locations
private void updateRentAmount() {
   String vehicleType = (String) jComboBox1.getSelectedItem();
    String startingLocation = (String) jComboBox3.getSelectedItem();
    String destinationLocation = (String) jComboBox4.getSelectedItem();

    if (vehicleType != null && startingLocation != null && destinationLocation != null) {
        HashMap<String, Integer> rates = rentMap.get(vehicleType);
        
        if (rates != null) {
            Integer rent = rates.get(destinationLocation);
            if (rent != null) {
                okk.setText(rent + " BDT");
            } else {
                okk.setText("Rent information not available for the selected destination.");
            }
        } else {
            okk.setText("No rates available for the selected vehicle type.");
        }
    } else {
        okk.setText("Please select all required fields.");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIRST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIRST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIRST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIRST.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FIRST().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ADDRESS;
    private javax.swing.JTextField MOBILE;
    private javax.swing.JTextField NAME;
    private javax.swing.JButton NEXT;
    private javax.swing.JTextField NID_NUMBER;
    private javax.swing.JButton button;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea ok;
    private javax.swing.JTextArea okk;
    private javax.swing.JButton submitt;
    // End of variables declaration//GEN-END:variables
}
